# Generated by Django 3.2.13 on 2022-12-02 05:39

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20221202_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
