# Generated by Django 3.2.13 on 2022-12-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gathering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatheringcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
