# Generated by Django 3.2.13 on 2022-12-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gathering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatherings',
            name='category',
            field=models.CharField(choices=[(None, '모집유형을 선택해주세요.'), ('모임', '모임'), ('스터디', '스터디')], default='모집유형을 선택해주세요.', max_length=10),
        ),
    ]
