# Generated by Django 3.2.13 on 2022-12-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gathering', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatherings',
            old_name='views',
            new_name='hits',
        ),
        migrations.RemoveField(
            model_name='gatherings',
            name='image',
        ),
    ]
