# Generated by Django 3.2.13 on 2022-12-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gathering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatherings',
            name='category',
            field=models.CharField(choices=[('모임', '모임'), ('스터디', '스터디')], default=None, max_length=10),
        ),
    ]
