# Generated by Django 3.2.13 on 2022-12-05 02:27

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notices',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
