# Generated by Django 3.2.13 on 2022-12-05 01:23

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
