# Generated by Django 3.2.13 on 2022-12-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_alter_notices_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
