# Generated by Django 3.2.13 on 2022-12-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_auto_20221205_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
