# Generated by Django 3.2.13 on 2022-12-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
