# Generated by Django 3.2.13 on 2022-12-04 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 14, 51, 24, 744722, tzinfo=utc)),
        ),
    ]
