# Generated by Django 3.2.13 on 2022-12-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(verbose_name='2022년 12월 10일 23:13'),
        ),
    ]
