# Generated by Django 3.2.13 on 2022-12-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomment1',
            name='unname',
            field=models.BooleanField(default=True),
        ),
    ]
