# Generated by Django 3.2.13 on 2022-12-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0002_alter_free_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='free',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
