# Generated by Django 3.2.13 on 2022-12-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0003_recomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReComment',
        ),
    ]
